//! Oracle-differential tests: the Rust port must reproduce Go ground
//! truth byte for byte on representative inputs.
//!
//! Vectors in `oracle_vectors.rs` were generated by running the Go owner
//! (`internal/release/build`) through the throwaway `zz-oracle-tmp`
//! driver; `tests/data/go-fixture.oci` and `tests/data/go-layout/` are
//! Go-produced bytes the Rust port inspects directly.

mod oracle_vectors;

use oracle_vectors as oracle;
use soda_build_tools::reader::settings::soda_commands;
use soda_release_build::confined_files::Root;
use soda_release_build::coreos::{https_url, CoreOSImage, VerifiedBase};
use soda_release_build::coreos_stream::{
    read_live_inputs, valid_live_inputs, valid_tailnet_inputs, write_live_inputs, LiveInputs,
    ResolvedCoreOS, TailnetInputs,
};
use soda_release_build::files::{is_digest, File};
use soda_release_build::forgejo::{forgejo_build_args, ForgejoToolchain, FORGEJO_COMPILER_IMAGE};
use soda_release_build::json_emit;
use soda_release_build::json_input::{read_json, read_json_at};
use soda_release_build::oci::{inspect_oci, inspect_oci_content};
use soda_release_build::oci_layout::inspect_oci_layout;
use soda_release_build::production::{Production, ResolvedInput};
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;

const FIXTURE_REVISION: &str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

fn data_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn scratch(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "soda-oracle-{}-{}-{}",
        tag,
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

#[test]
fn oracle_go_fixture_identity() {
    let image = inspect_oci(&data_path("go-fixture.oci"), "x86_64", FIXTURE_REVISION).unwrap();
    assert_eq!(image.manifest, oracle::OCI_MANIFEST);
    assert_eq!(image.config, oracle::OCI_CONFIG);
    assert_eq!(image.architecture, oracle::OCI_ARCH);
    assert_eq!(image.revision, oracle::OCI_REVISION);
    assert_eq!(image.source, oracle::OCI_SOURCE);
    assert_eq!(image.base_name, oracle::OCI_BASENAME);
    assert_eq!(image.base_digest, oracle::OCI_BASEDIGEST);
}

#[test]
fn oracle_go_fixture_rejections() {
    let file = data_path("go-fixture.oci");
    assert_eq!(
        inspect_oci(&file, "aarch64", FIXTURE_REVISION)
            .unwrap_err()
            .message(),
        oracle::OCI_ERR_ARCH
    );
    assert_eq!(
        inspect_oci(&file, "x86_64", &"c".repeat(40))
            .unwrap_err()
            .message(),
        oracle::OCI_ERR_REVISION
    );
    let dir = scratch("tamper");
    let tampered = dir.join("tampered.oci");
    let bytes = std::fs::read(&file).unwrap();
    let needle = b"synthetic layer";
    let pos = bytes
        .windows(needle.len())
        .position(|w| w == needle)
        .unwrap();
    let mut tampered_bytes = bytes;
    tampered_bytes[pos..pos + needle.len()].copy_from_slice(b"tampered! layer");
    std::fs::write(&tampered, tampered_bytes).unwrap();
    assert_eq!(
        inspect_oci(&tampered, "x86_64", FIXTURE_REVISION)
            .unwrap_err()
            .message(),
        oracle::OCI_ERR_TAMPERED
    );
}

#[test]
fn oracle_go_fixture_content() {
    let file = data_path("go-fixture.oci");
    let (image, content) = inspect_oci_content(
        &file,
        "x86_64",
        FIXTURE_REVISION,
        &[String::from("/fixture.txt")],
    )
    .unwrap();
    assert_eq!(image.config, oracle::OCI_CONFIG);
    assert_eq!(
        content.get("/fixture.txt").unwrap(),
        oracle::OCI_FIXTURE_HASH
    );
    assert_eq!(
        inspect_oci_content(
            &file,
            "x86_64",
            FIXTURE_REVISION,
            &[String::from("/missing")]
        )
        .unwrap_err()
        .message(),
        oracle::OCI_ERR_MISSING
    );
}

#[test]
fn oracle_go_layout() {
    let dir = data_path("go-layout");
    let mut revisions = HashMap::new();
    revisions.insert(oracle::OCI_CONFIG.to_string(), FIXTURE_REVISION.to_string());
    let got = inspect_oci_layout(&dir, "x86_64", &revisions).unwrap();
    assert_eq!(got.images.len(), oracle::LAYOUT_IMAGES);
    assert_eq!(got.files.len(), oracle::LAYOUT_FILES);
    assert_eq!(got.bytes, oracle::LAYOUT_BYTES);
    assert_eq!(
        got.files.get("index.json").unwrap(),
        oracle::LAYOUT_INDEXHASH
    );
    let mut total = 0u64;
    for (name, hash) in &got.files {
        let bytes = std::fs::read(dir.join(name)).unwrap();
        assert_eq!(&soda_release_build::sha256_hex(&bytes), hash);
        total += bytes.len() as u64;
    }
    assert_eq!(total, got.bytes);
    assert_eq!(
        inspect_oci_layout(&dir, "aarch64", &revisions)
            .unwrap_err()
            .message(),
        oracle::LAYOUT_ERR_ARCH
    );
}

fn oracle_live_inputs() -> LiveInputs {
    let img = CoreOSImage {
        url: "https://builds.test/fedora-coreos-44.20260901.1.0-live.x86_64.iso".to_string(),
        signature_url: "https://builds.test/fedora-coreos-44.20260901.1.0-live.x86_64.iso.sig"
            .to_string(),
        sha256: "a".repeat(64),
        uncompressed_sha256: "b".repeat(64),
    };
    let mut container = HashMap::new();
    container.insert(
        "x86_64".to_string(),
        format!("quay.io/fedora/fedora-coreos@sha256:{}", "c".repeat(64)),
    );
    let mut iso = HashMap::new();
    iso.insert("x86_64".to_string(), img.clone());
    let mut qemu = HashMap::new();
    qemu.insert("x86_64".to_string(), img);
    LiveInputs {
        coreos: ResolvedCoreOS {
            release: "44.20260901.1.0".to_string(),
            metadata_url:
                "https://builds.test/prod/streams/stable/builds/44.20260901.1.0/release.json"
                    .to_string(),
            container,
            iso,
            qemu,
        },
        tailnet: TailnetInputs {
            version: "1.98.2".to_string(),
            sha256: "e".repeat(64),
            base: "docker.io/tailscale/alpine-base:3.22".to_string(),
        },
    }
}

#[test]
fn oracle_live_inputs_bytes() {
    let inputs = oracle_live_inputs();
    assert_eq!(inputs.marshal() + "\n", oracle::LIVE_INPUTS_JSON);
    let dir = scratch("live");
    let path = dir.join("live-inputs.json");
    write_live_inputs(&path, &inputs).unwrap();
    assert_eq!(
        std::fs::read_to_string(&path).unwrap(),
        oracle::LIVE_INPUTS_JSON
    );
    assert_eq!(read_live_inputs(&path).unwrap(), inputs);
    let mut bad = inputs.clone();
    bad.tailnet.version = "yesterday".to_string();
    assert_eq!(
        valid_live_inputs(&bad).unwrap_err().message(),
        oracle::LIVE_ERR_TAILNET
    );
    let mut bad = inputs.clone();
    bad.coreos.release = "tomorrow".to_string();
    assert_eq!(
        valid_live_inputs(&bad).unwrap_err().message(),
        oracle::LIVE_ERR_RELEASE
    );
    let mut bad = inputs;
    bad.coreos.container = HashMap::new();
    assert_eq!(
        valid_live_inputs(&bad).unwrap_err().message(),
        oracle::LIVE_ERR_CONTAINER
    );
}

#[test]
fn oracle_verified_base_bytes() {
    let base = VerifiedBase {
        path: "$OUT/coreos.qcow2".to_string(),
        sha256: "a".repeat(64),
        architecture: "x86_64".to_string(),
        release: "44.20260901.1.0".to_string(),
        signer: "ABC".to_string(),
    };
    assert_eq!(base.marshal() + "\n", oracle::VERIFIED_BASE_JSON);
}

#[test]
fn oracle_resolved_inputs_bytes() {
    let inputs = [ResolvedInput {
        requested: "docker.io/rockylinux/rockylinux:10.2".to_string(),
        reference: format!("docker.io/rockylinux/rockylinux@sha256:{}", "b".repeat(64)),
        config: oracle::OCI_CONFIG.to_string(),
    }];
    let body = json_emit::marshal_indent(&json_emit::Emit::List(
        inputs.iter().map(ResolvedInput::emit).collect(),
    )) + "\n";
    assert_eq!(body, oracle::RESOLVED_INPUTS_JSON);
}

#[test]
fn oracle_forgejo_argv_and_script() {
    let mut prod = Production::default();
    prod.native = "$ROOT/native".to_string();
    prod.forgejo_source = "$ROOT/frozen-fork".to_string();
    prod.forgejo_revision = FIXTURE_REVISION.to_string();
    let args = forgejo_build_args(&prod, "amd64");
    let (argv, script) = args.split_at(args.len() - 1);
    assert_eq!(argv.join("\n") + "\n", oracle::FORGEJO_ARGV);
    assert_eq!(script[0].clone() + "\n", oracle::FORGEJO_SCRIPT);
}

#[test]
fn oracle_forgejo_toolchain_bytes() {
    let toolchain = ForgejoToolchain {
        compiler_image: FORGEJO_COMPILER_IMAGE.to_string(),
        apk_packages: vec![
            "build-base-0.5-r4".to_string(),
            "gcc-14.2.0-r6".to_string(),
            "musl-dev-1.2.5-r10".to_string(),
        ],
    };
    toolchain.validate().unwrap();
    assert_eq!(toolchain.marshal() + "\n", oracle::FORGEJO_TOOLCHAIN_JSON);
}

fn fixture_elf() -> [u8; 64] {
    let mut elf = [0u8; 64];
    elf[0..7].copy_from_slice(&[0x7f, b'E', b'L', b'F', 2, 1, 1]);
    elf[16..18].copy_from_slice(&2u16.to_le_bytes());
    elf[18..20].copy_from_slice(&62u16.to_le_bytes());
    elf[20..24].copy_from_slice(&1u32.to_le_bytes());
    elf[52..54].copy_from_slice(&64u16.to_le_bytes());
    elf
}

#[test]
fn oracle_production_sequence() {
    let root = scratch("prodseq");
    let out = root.join(".artifacts/native/x86_64");
    std::fs::create_dir_all(&out).unwrap();
    for (name, body) in [
        (
            "package.json",
            "{\"packageManager\":\"bun@1.4.2\",\"unrelated\":true}",
        ),
        (
            "system/project/Containerfile",
            "ARG BASE_IMAGE=docker.io/rockylinux/rockylinux:10.2\n",
        ),
        (
            "system/containers/dashboard/Containerfile",
            "ARG BASE_IMAGE=docker.io/rockylinux/rockylinux:10.2\n",
        ),
        (
            "system/host/services/forgejo.container",
            "[Container]\nImage=codeberg.org/forgejo/forgejo:15.0.9\n",
        ),
        (
            "system/host/services/soda-proxy.container",
            "[Container]\nImage=docker.io/library/caddy:2\n",
        ),
    ] {
        let path = root.join(name);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, body).unwrap();
    }
    // The Go-built seed keeps config IDs identical to the oracle.
    let seed_bytes = std::fs::read(data_path("go-fixture.oci")).unwrap();
    let seed_path = root.join("seed.oci");
    std::fs::write(&seed_path, &seed_bytes).unwrap();
    let seed_image = inspect_oci(&seed_path, "x86_64", FIXTURE_REVISION).unwrap();
    assert_eq!(seed_image.config, oracle::OCI_CONFIG);
    let live_path = root.join("live-inputs.json");
    write_live_inputs(&live_path, &oracle_live_inputs()).unwrap();
    let calls = Arc::new(std::sync::Mutex::new(Vec::<String>::new()));
    let mut prod = Production::default();
    prod.source = root.to_string_lossy().into_owned();
    prod.native = out.to_string_lossy().into_owned();
    prod.out = out.to_string_lossy().into_owned();
    prod.arch = "x86_64".to_string();
    prod.revision = FIXTURE_REVISION.to_string();
    prod.live_inputs = live_path.to_string_lossy().into_owned();
    let calls_next = calls.clone();
    prod.next = Some(Box::new(move |label| {
        calls_next.lock().unwrap().push(format!("STEP {label}"));
        Ok(())
    }));
    let calls_capture = calls.clone();
    let config = seed_image.config.clone();
    prod.capture = Some(Box::new(move |_dir, name, args| {
        calls_capture
            .lock()
            .unwrap()
            .push(format!("{name} {}", args.join(" ")));
        if name == "bun" {
            return Ok("1.4.2".to_string());
        }
        if args[1] == "pull" {
            return Ok(config.clone());
        }
        Ok(format!("sha256:{}", "b".repeat(64)))
    }));
    let calls_exec = calls.clone();
    let image_config = seed_image.config.clone();
    prod.execute = Some(Box::new(move |dir, name, args| {
        calls_exec
            .lock()
            .unwrap()
            .push(format!("{name} {}", args.join(" ")));
        if name == "go" && args.first().map(String::as_str) == Some("build") {
            for (i, arg) in args.iter().enumerate() {
                if arg == "-o" {
                    let dest = PathBuf::from(&args[i + 1]);
                    std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
                    std::fs::write(&dest, fixture_elf()).unwrap();
                    return Ok(());
                }
            }
        }
        if name == "cargo" && args.first().map(String::as_str) == Some("build") {
            for (i, arg) in args.iter().enumerate() {
                if arg == "-p" && i + 1 < args.len() {
                    // Post-A01 fold, -p soda-project-terminal builds both
                    // bins like cargo; every other package keeps one.
                    let bins: Vec<&str> = match args[i + 1].as_str() {
                        "soda-project-terminal" => vec!["project-terminal", "project-account"],
                        "soda-project-factory-roles" => vec!["project-factory-roles"],
                        pkg => vec![pkg],
                    };
                    for bin in bins {
                        let dest = PathBuf::from(dir).join("target/release").join(bin);
                        std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
                        std::fs::write(&dest, fixture_elf()).unwrap();
                    }
                    return Ok(());
                }
            }
        }
        if name != "podman" {
            return Ok(());
        }
        for (i, arg) in args.iter().enumerate() {
            if arg == "--iidfile" {
                return soda_release_build::files::write_new(
                    std::path::Path::new(&args[i + 1]),
                    image_config.as_bytes(),
                    0o600,
                );
            }
            if arg == "--output" {
                return soda_release_build::files::write_new(
                    std::path::Path::new(&args[i + 1]),
                    &seed_bytes,
                    0o600,
                );
            }
        }
        panic!("unexpected execution: {args:?}");
    }));
    let host = out.join("context").to_string_lossy().into_owned();
    let forgejo = out.join("forgejo-context").to_string_lossy().into_owned();
    prod.dependencies().unwrap();
    prod.resolve_inputs().unwrap();
    prod.assets(&host, &forgejo).unwrap();
    let images = prod.images(&forgejo).unwrap();
    assert_eq!(images.len(), 6);
    let root_str = root.to_string_lossy().into_owned();
    let normalized: Vec<String> = calls
        .lock()
        .unwrap()
        .iter()
        .map(|call| call.replace(&root_str, "$ROOT"))
        .collect();
    assert_eq!(normalized.join("\n") + "\n", oracle::PRODUCTION_SEQUENCE);
    let app_inputs = std::fs::read_to_string(out.join("app-inputs.json")).unwrap();
    assert_eq!(
        app_inputs.replace(&root_str, "$ROOT"),
        oracle::APP_INPUTS_JSON
    );
}

#[test]
fn oracle_misc_vectors() {
    assert_eq!(
        soda_release_build::files::oci_architecture("aarch64")
            .unwrap_err()
            .message(),
        oracle::MISC_OCI_ARCH
    );
    assert_eq!(
        https_url("http://example.test/base"),
        oracle::MISC_HTTPS_HTTP
    );
    assert_eq!(
        valid_tailnet_inputs(&TailnetInputs {
            version: "x".to_string(),
            sha256: "y".to_string(),
            base: "z".to_string(),
        })
        .unwrap_err()
        .message(),
        oracle::MISC_TAILNET
    );
    assert!(soda_commands(&scratch("missing-cmds").join("cmd")).is_err());
}

#[test]
fn oracle_read_json_strictness() {
    let dir = scratch("readjson");
    let path = dir.join("strict.json");
    std::fs::write(
        &path,
        format!(
            "{{\"sha256\":\"{}\",\"mode\":420,\"directory\":true,\"bogus\":1}}",
            "a".repeat(64)
        ),
    )
    .unwrap();
    let err = read_json::<File>(&path, "build.File", File::decode).unwrap_err();
    assert_eq!(err.message(), oracle::READ_UNKNOWN_FIELD);
    std::fs::write(&path, "{\"mode\":420} {}").unwrap();
    let err = read_json::<File>(&path, "build.File", File::decode).unwrap_err();
    assert_eq!(err.message(), oracle::READ_TRAILING);
    std::fs::write(&path, "{\"mode\":420}").unwrap();
    let file: File = read_json(&path, "build.File", File::decode).unwrap();
    assert_eq!(file.mode, oracle::READ_OK_MODE);
    assert!(is_digest(&"a".repeat(64)));
    let root = Root::open(&dir).unwrap();
    let (back, _digest): (File, String) =
        read_json_at(&root, "strict.json", "build.File", File::decode).unwrap();
    assert_eq!(back.mode, oracle::READ_OK_MODE);
}
