import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {startSpacesPreview} from '../../scripts/preview-spaces.ts';
import {captureSpacesComponent} from '../../scripts/screenshot.ts';

test('local fixture supports the full journey, simulated IO, persistent reload and scoped resets', async t => {
  const server = await startSpacesPreview(0);
  const browser = await chromium.launch({headless: true, chromiumSandbox: true});
  t.after(async () => {await browser.close(); server.stop();});
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}}), errors: string[] = [];
  page.setDefaultTimeout(5000);
  page.on('pageerror', error => errors.push(error.message));
  const writes: string[] = [];
  let output = '';
  page.on('websocket', socket => socket.on('framereceived', ({payload}) => {
    const frame = JSON.parse(String(payload));
    if (frame.type === 'output') output += Buffer.from(frame.data, 'base64').toString('utf8');
  }));
  page.on('request', req => {if (req.method() === 'POST' && new URL(req.url()).pathname.startsWith('/-/soda/api/')) writes.push(new URL(req.url()).pathname);});
  await page.goto(server.url.href);
  await page.getByRole('heading', {name: 'Create your first project'}).waitFor();
  await captureSpacesComponent(page, 'dev-welcome');
  await page.getByRole('button', {name: 'Create project', exact: true}).click();
  await page.getByRole('radio', {name: /alice\/Alpha/}).check();
  await page.getByRole('button', {name: 'Continue', exact: true}).click();
  await page.getByRole('button', {name: 'Create project', exact: true}).click();
  await page.getByRole('button', {name: 'Join project', exact: true}).click();
  await page.getByRole('button', {name: 'New terminal', exact: true}).click();
  await page.locator('.soda-workspace-terminal:visible .is-connected').waitFor();
  const input = page.locator('.xterm-helper-textarea');
  await input.pressSequentially('echo local-fixture'); await input.press('Enter');
  await page.waitForTimeout(100);
  assert(output.includes('\r\nlocal-fixture\r\n'), 'mock shell did not return command output');
  assert.equal(writes.filter(path => path.endsWith('/api/environments')).length, 1);
  assert.equal(writes.filter(path => path.endsWith('/join')).length, 1);
  assert.equal(writes.filter(path => path.endsWith('/terminal-sessions')).length, 1);
  const writesBeforeReload = writes.length;
  output = '';
  await page.reload();
  await page.locator('.soda-workspace-terminal:visible .is-connected').waitFor();
  assert(output.includes('\r\nlocal-fixture\r\n'), 'reload lost mock terminal output');
  assert.equal(writes.length, writesBeforeReload, 'reload replayed a product write');
  await page.getByLabel('Start at', {exact: true}).selectOption('split');
  await page.waitForFunction(() => document.querySelectorAll('.soda-workspace-terminal:not([hidden]) .is-connected').length === 2);
  await captureSpacesComponent(page, 'dev-split');
  const widths = await page.locator('.soda-workspace-terminal:visible').evaluateAll(nodes => nodes.map(n => n.getBoundingClientRect().width));
  assert(widths.every(width => width > 550));
  await page.getByLabel('Theme', {exact: true}).selectOption('light');
  await page.setViewportSize({width: 390, height: 844});
  assert(await page.locator('.soda-workspace').evaluate(n => n.scrollWidth <= n.clientWidth));
  await captureSpacesComponent(page, 'dev-mobile');
  await page.getByLabel('Start at', {exact: true}).selectOption('expired');
  await page.getByRole('link', {name: 'Reconnect to Forgejo', exact: true}).waitFor();
  assert.equal(await page.getByRole('button', {name: 'Reload Spaces', exact: true}).count(), 0);
  await page.getByRole('link', {name: 'Reconnect to Forgejo', exact: true}).click();
  await page.getByRole('button', {name: 'New terminal', exact: true}).waitFor();
  const second = await browser.newPage(); await second.goto(server.url.href);
  await second.getByRole('heading', {name: 'Create your first project'}).waitFor();
  assert.equal(await page.getByRole('heading', {name: 'Create your first project'}).count(), 0, 'another browser reset this fixture');
  assert.deepEqual(errors, []);
});

test('fixture HTTP host/origin restrictions and arbitrary paths do not proxy or expose files', async t => {
  const server = await startSpacesPreview(0); t.after(() => server.stop());
  const homepage = await fetch(server.url);
  const cookie = homepage.headers.get('set-cookie')?.split(';')[0]; assert(cookie);
  assert.equal((await fetch(new URL('/_fixture/reset', server.url), {method: 'POST', headers: {Cookie: cookie, Origin: 'http://unrelated.invalid', 'Content-Type': 'application/json'}, body: JSON.stringify({scenario: 'working'})})).status, 403);
  assert.equal((await fetch(new URL('/package.json', server.url), {headers: {Cookie: cookie}})).status, 404);
  assert.equal((await fetch(server.url, {headers: {Host: 'unrelated.invalid'}})).status, 403);
});
