[package]
name = "soda-stage-render"
version = "0.1.0"
edition = "2021"

[lib]
name = "soda_stage_render"
path = "src/lib.rs"

[[bin]]
name = "soda-stage"
path = "src/bin/soda-stage.rs"

[[bin]]
name = "soda-render-provisioning"
path = "src/bin/soda-render-provisioning.rs"

[[bin]]
name = "soda-render-terminal-logo"
path = "src/bin/soda-render-terminal-logo.rs"

[dependencies]
soda-json = { path = "../soda-json" }
sha2 = "0.10"
