/// `HELP_HEADER` is the retired script's lines 2-10 verbatim: `help` printed
/// them via `sed -n '2,10p' "$0"`, so the port embeds the same bytes.
pub(crate) const HELP_HEADER: &str = "# rotate-lab-creds.sh — lab credential inventory and owner-gated rotation (B7).\n#\n# Context: the D3 rootfs HTTP exposure served live guest disks and images\n# world-readable over HTTP. Any secret that ever lived in those bytes must\n# be treated as exposed until the owner rotates it. Rotation itself is an\n# explicit owner decision: this script defaults to read-only inventory and\n# prints runbooks; only --execute with SODA_ROTATE_ACK=<class> mutates, and\n# only for fully scriptable classes. Secrets travel via 0600 files, never\n# argv, environment values in logs, or stdout.\n";

pub(crate) const RUNBOOK_FIXTURE: &str = "-- runbook: fixture-authority (fully scriptable with --execute)\nRegenerates the fixture-only media authority (never release keys):\n  SODA_ROTATE_ACK=fixture-authority cargo run -p soda-rotate-lab-creds --rotate fixture-authority --execute\nEffect: old fixture signatures stop verifying; in-flight development\nattempts using the old authority fail closed and must rerun setup.\n";

pub(crate) const RUNBOOK_CLOUDFLARED: &str = "-- runbook: cloudflared-token (owner-manual; dashboard-issued)\n1. Rotate the tunnel token in the Cloudflare dashboard.\n2. As root, install it with secret-file handling only:\n     install -m 0640 -o root -g cloudflared /path/to/new.token \\\n       /etc/cloudflared/dimensionlab-forgejo-https.token\n   Never pass the token on a command line; shred the staging copy after.\n3. Restart the tunnel service and re-run this script (inventory).\n";

pub(crate) const RUNBOOK_RUNNER: &str = "-- runbook: forgejo-runner (owner-manual; needs a Forgejo admin token)\n1. Revoke the runner registration in Forgejo and create a new token.\n2. Stop the runner, replace the secret file (0600) without argv exposure,\n   re-register, and restart the runner.\n3. Re-run this script (inventory) to confirm modes.\n";

pub(crate) const RUNBOOK_LAB_VM: &str = "-- runbook: lab-vm-operator (owner-manual; protected VMs)\nGuest operator credentials possibly baked into the served QCOW2s cannot be\naudited from the host (live disks are never mounted here). After the D3\nreplacement is installed, rotate operator/SSH material from the guest\nconsoles, then record the rotation date with the owner.\n";
