[package]
name = "soda-forgejo-locales"
version = "0.1.0"
edition = "2021"

[lib]
name = "soda_forgejo_locales"
path = "src/lib.rs"

[[bin]]
name = "soda-forgejo-locales"
path = "src/bin/soda-forgejo-locales.rs"

[dependencies]
soda-json = { path = "../../lib/json" }
ureq = { version = "2", default-features = false, features = ["tls"] }
sha2 = "0.10"
