import { useEffect, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { Alert, Button, Form, FormGroup, Spinner, TextInput } from "@patternfly/react-core";
import { APIError, request, type Session } from "./api";
import { useSession } from "./session";
import { repositoryPath } from "./repositories";
interface Secret { name: string; created_at: string }
interface Variable { name: string; data: string }
export function ActionConfiguration({ session }: { session: Session }) {
 const { owner = "", repo = "", org } = useParams(); const [query, setQuery] = useSearchParams(); const kind = query.get("kind") === "variables" ? "variables" : "secrets"; const page = query.get("page") ?? "1";
 const api = org ? `/api/forgejo/organizations/${encodeURIComponent(org)}/actions` : `/api/forgejo/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/actions`;
 const [items, setItems] = useState<(Secret | Variable)[] | null>(null); const [next, setNext] = useState<number | null>(null); const [attempt, setAttempt] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
 const [name, setName] = useState(""); const [value, setValue] = useState(""); const [editing, setEditing] = useState(false); const [message, setMessage] = useState("");
 useEffect(() => { setName(""); setValue(""); setEditing(false); setMessage(""); }, [api, kind]);
 useEffect(() => { const controller = new AbortController(); setItems(null); setError(""); request<{ items: (Secret | Variable)[]; next_page: number | null }>(`${api}/${kind}?page=${encodeURIComponent(page)}`, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) { setItems(result.items); setNext(result.next_page); } }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Native configuration unavailable."); }); return () => controller.abort(); }, [api, kind, page, attempt, session]);
 async function change(remove: boolean, target = name) {
  if (busy) return; if (remove && !window.confirm(`Delete native ${kind === "secrets" ? "secret" : "variable"} ${target}? Workflows may depend on it.`)) return;
  const body = remove ? {} : kind === "secrets" ? { data: value } : { value }; setBusy(true); setError(""); setMessage(""); if (kind === "secrets") setValue("");
  try { await request(`${api}/${kind}/${encodeURIComponent(target)}`, { method: remove ? "DELETE" : kind === "secrets" || editing ? "PUT" : "POST", csrf: session.csrf_token, body }); if (useSession.getState().session !== session) return; setValue(""); setName(""); setEditing(false); setMessage(remove ? "Native configuration deleted." : "Native configuration saved."); setAttempt(previous => previous + 1); }
  catch (failure) { if (useSession.getState().session !== session) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(`${failure instanceof Error ? failure.message : "Change not confirmed."} Inspect native state before retrying. Secret values are not retained for retry.`); } finally { setBusy(false); }
 }
 return <section aria-busy={busy}><h1>Actions configuration: {org ?? `${owner}/${repo}`}</h1>{org ? <Link to={`/organizations/${encodeURIComponent(org)}`}>Organization</Link> : <Link to={`${repositoryPath(owner, repo)}/actions`}>Actions</Link>}<p>Forgejo enforces the native repository or organization administration permission. Secrets are write-only; non-secret variables are readable by authorized users. Neither is stored in Soda's database or browser persistence.</p>
 <label>Configuration type <select value={kind} disabled={busy} onChange={event => setQuery({ kind: event.currentTarget.value, page: "1" })}><option value="secrets">Secrets (write-only)</option><option value="variables">Non-secret variables</option></select></label>{error && <Alert isInline variant="danger" title={error} />}{message && <p role="status">{message}</p>}{!items && !error && <Spinner aria-label="Reading native configuration" />}
 <ul>{items?.map(item => <li key={item.name}><strong>{item.name}</strong>{"data" in item ? <pre>{item.data}</pre> : <> — value hidden; created {item.created_at}</>}<Button variant="link" isDisabled={busy} onClick={() => { setName(item.name); setValue("data" in item ? item.data : ""); setEditing(true); setMessage(""); }}>Edit {item.name}</Button><Button variant="danger" isDisabled={busy} onClick={() => void change(true, item.name)}>Delete {item.name}</Button></li>)}</ul>{items?.length === 0 && <p>No native entries on this page.</p>}
 <Button variant="secondary" isDisabled={busy || Number(page) <= 1} onClick={() => setQuery({ kind, page: String(Number(page) - 1) })}>Previous page</Button><Button variant="secondary" isDisabled={busy || !items || next === null} onClick={() => next !== null && setQuery({ kind, page: String(next) })}>Next page</Button>
 <h2>{editing ? "Replace native value" : "Add native configuration"}</h2>{editing && <Button variant="link" isDisabled={busy} onClick={() => { setEditing(false); setName(""); setValue(""); }}>Switch to new entry</Button>}
 <Form onSubmit={event => { event.preventDefault(); void change(false); }}><FormGroup label="Name" fieldId="action-name"><TextInput id="action-name" value={name} isDisabled={busy || editing} maxLength={255} onChange={(_, text) => setName(text)} /></FormGroup><FormGroup label={kind === "secrets" ? "Secret value (write-only)" : "Non-secret variable value"} fieldId="action-value">{kind === "secrets" ? <TextInput id="action-value" type="password" autoComplete="new-password" value={value} isDisabled={busy} maxLength={32768} onChange={(_, text) => setValue(text)} /> : <textarea id="action-value" value={value} disabled={busy} maxLength={32768} onChange={event => setValue(event.currentTarget.value)} />}</FormGroup><p>Saving a secret replaces an existing value with the same native name. Empty values are explicit replacements, not a request to keep the old value.</p><Button type="submit" isDisabled={busy || !name}>Save native {kind === "secrets" ? "secret" : "variable"}</Button></Form></section>;
}
