import { useEffect, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { Alert, Button, Form, FormGroup, Spinner, TextInput } from "@patternfly/react-core";
import { APIError, request, type Session } from "./api";
import { useSession } from "./session";
import { repositoryPath } from "./repositories";
interface Run { id: string; number: string; title: string; workflow: string; sha: string; ref: string; status: string; event: string; created: string; updated: string; need_approval: boolean }
interface Task { id: string; run_number: string; name: string; title: string; status: string; sha: string; ref: string; workflow: string }
interface Workflow { name: string; path: string; sha: string }
export function Actions({ session }: { session: Session }) {
 const { owner = "", repo = "" } = useParams(); const [query, setQuery] = useSearchParams(); const page = query.get("page") ?? "1"; const status = query.get("status") ?? "";
 const api = `/api/forgejo/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/actions`; const base = repositoryPath(owner, repo);
 const [runs, setRuns] = useState<Run[] | null>(null); const [next, setNext] = useState<number | null>(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0);
 useEffect(() => { const controller = new AbortController(); setRuns(null); setError(""); request<{ items: Run[]; next_page: number | null }>(`${api}/runs?${new URLSearchParams({ page, status })}`, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) { setRuns(value.items); setNext(value.next_page); } }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Runs unavailable."); }); return () => controller.abort(); }, [api, page, status, attempt, session]);
 return <section><h1>Actions: {owner}/{repo}</h1><nav><Link to={base}>Repository</Link><Link to={`${base}/actions/workflows`}>Workflows and dispatch</Link><Link to={`${base}/actions/tasks`}>Repository tasks</Link><Link to={`${base}/actions/configuration`}>Secrets and variables</Link></nav><p>Forgejo schedules and records runs. Local runner capacity remains in operator Cockpit.</p>
 <label>Status <select value={status} onChange={event => setQuery({ status: event.currentTarget.value, page: "1" })}><option value="">All statuses</option>{["unknown", "waiting", "running", "success", "failure", "cancelled", "skipped", "blocked"].map(value => <option key={value}>{value}</option>)}</select></label><Button variant="secondary" onClick={() => setAttempt(value => value + 1)}>Refresh runs</Button>
 {error && <Alert isInline variant="danger" title={error} />}{!runs && !error && <Spinner aria-label="Loading runs" />}<ul>{runs?.map(run => <li key={run.id}><Link to={`${base}/actions/runs/${run.id}`}>#{run.number} {run.title}</Link> — {run.status} — {run.workflow} — {run.ref}</li>)}</ul>{runs?.length === 0 && <p>No native runs match this page.</p>}
 <Button variant="secondary" isDisabled={Number(page) <= 1} onClick={() => setQuery({ page: String(Number(page) - 1), status })}>Previous page</Button><Button variant="secondary" isDisabled={!runs || next === null} onClick={() => next !== null && setQuery({ page: String(next), status })}>Next page</Button></section>;
}
export function ActionRunDetail({ session }: { session: Session }) {
 const { owner = "", repo = "", run = "" } = useParams(); const api = `/api/forgejo/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/actions/runs/${encodeURIComponent(run)}`; const base = repositoryPath(owner, repo);
 const [data, setData] = useState<Run | null>(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0); const [observed, setObserved] = useState("");
 useEffect(() => { const controller = new AbortController(); let timer: ReturnType<typeof setTimeout> | undefined; setData(null); setError("");
 async function load() { try { const value = await request<Run>(api, { signal: controller.signal }); if (controller.signal.aborted) return; setData(value); setObserved(new Date().toLocaleTimeString()); if (!["success", "failure", "cancelled", "skipped"].includes(value.status)) timer = setTimeout(() => { void load(); }, 5000); } catch (failure) { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Run refresh failed."); } }
 void load(); return () => { controller.abort(); if (timer) clearTimeout(timer); }; }, [api, session, attempt]);
 return <section><h1>Native run</h1><Link to={`${base}/actions`}>Actions</Link><Button variant="secondary" onClick={() => setAttempt(value => value + 1)}>Refresh run</Button>{error && <Alert isInline variant="danger" title={error} />}{!data && !error && <Spinner aria-label="Loading run" />}{data && <><h2>#{data.number} {data.title}</h2><p role="status">{data.status} — last read {observed}{error ? " (refresh stopped; stale data)" : ""}</p><dl><dt>Workflow</dt><dd>{data.workflow}</dd><dt>Ref</dt><dd>{data.ref}</dd><dt>Commit</dt><dd><Link to={`${base}/commits/${encodeURIComponent(data.sha)}`}>{data.sha}</Link></dd><dt>Event</dt><dd>{data.event}</dd><dt>Updated upstream</dt><dd>{data.updated}</dd></dl>{data.need_approval && <p>Forgejo reports that this run needs approval.</p>}<p>Jobs, logs, artifacts and run controls are not yet available in Soda. Their backend interfaces still require integration; these are incomplete required workflows. Active status refreshes every five seconds while this view is mounted; errors stop polling.</p></>}</section>;
}
export function ActionTasks({ session }: { session: Session }) {
 const { owner = "", repo = "" } = useParams(); const [query, setQuery] = useSearchParams(); const page = query.get("page") ?? "1"; const base = repositoryPath(owner, repo); const api = `/api/forgejo/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/actions/tasks?page=${encodeURIComponent(page)}`;
 const [items, setItems] = useState<Task[] | null>(null); const [next, setNext] = useState<number | null>(null); const [error, setError] = useState("");
 useEffect(() => { const controller = new AbortController(); setItems(null); setError(""); request<{ items: Task[]; next_page: number | null }>(api, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) { setItems(value.items); setNext(value.next_page); } }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Tasks unavailable."); }); return () => controller.abort(); }, [api, session]);
 return <section><h1>Repository task records</h1><Link to={`${base}/actions`}>Actions</Link><p>Native task records across the repository, not a complete per-run job/step graph. Pending jobs without tasks may not appear.</p>{error && <Alert isInline variant="danger" title={error} />}{!items && !error && <Spinner aria-label="Loading tasks" />}<ul>{items?.map(task => <li key={task.id}>{task.name} — {task.status} — run #{task.run_number} — {task.ref} — {task.workflow}</li>)}</ul>{items?.length === 0 && <p>No task records on this page.</p>}<Button variant="secondary" isDisabled={Number(page) <= 1} onClick={() => setQuery({ page: String(Number(page) - 1) })}>Previous page</Button><Button variant="secondary" isDisabled={!items || next === null} onClick={() => next !== null && setQuery({ page: String(next) })}>Next page</Button></section>;
}
export function Workflows({ session }: { session: Session }) {
 const { owner = "", repo = "" } = useParams(); const [query, setQuery] = useSearchParams(); const ref = query.get("ref") ?? ""; const [draftRef, setDraftRef] = useState(ref); const base = repositoryPath(owner, repo); const api = `/api/forgejo/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/actions`;
 const [files, setFiles] = useState<Workflow[] | null>(null); const [selected, setSelected] = useState(""); const [inputs, setInputs] = useState("{}"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [result, setResult] = useState<{ id: string; number: string } | null>(null);
 useEffect(() => { const controller = new AbortController(); setFiles(null); setSelected(""); setInputs("{}"); setResult(null); setError(""); if (ref) request<{ items: Workflow[] }>(`${api}/workflows?${new URLSearchParams({ ref })}`, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) setFiles(value.items); }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Workflows unavailable."); }); return () => controller.abort(); }, [api, ref, session]);
 async function dispatch() { if (busy) return; let parsed: unknown; try { parsed = JSON.parse(inputs); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object" || Object.values(parsed).some(value => typeof value !== "string")) throw new Error(); } catch { setError("Inputs must be a JSON object containing string values."); return; } setBusy(true); setError(""); setResult(null); try { const value = await request<{ id: string; number: string }>(`${api}/workflows/${encodeURIComponent(selected)}/dispatch`, { method: "POST", csrf: session.csrf_token, body: { ref, inputs: parsed } }); if (useSession.getState().session === session) { setInputs("{}"); setResult(value); } } catch (failure) { if (useSession.getState().session !== session) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(`${failure instanceof Error ? failure.message : "Dispatch not confirmed."} Check native runs before retrying; the request may have started a run.`); } finally { setBusy(false); } }
 return <section aria-busy={busy}><h1>Workflows and explicit dispatch</h1><Link to={`${base}/actions`}>Actions</Link><Form onSubmit={event => { event.preventDefault(); setQuery({ ref: draftRef }); }}><FormGroup label="Native ref" fieldId="workflow-ref"><TextInput id="workflow-ref" value={draftRef} isDisabled={busy} onChange={(_, value) => setDraftRef(value)} /></FormGroup><Button type="submit" isDisabled={busy || !draftRef}>Read workflow files</Button></Form>{error && <Alert isInline variant="danger" title={error} />}{ref && !files && !error && <Spinner aria-label="Reading workflows" />}<ul>{files?.map(file => <li key={file.path}><Link to={`${base}?${new URLSearchParams({ ref, path: file.path })}`}>{file.path}</Link><Button variant="link" isDisabled={busy} onClick={() => { setSelected(file.name); setResult(null); }}>Select {file.name}</Button></li>)}</ul>{files?.length === 0 && <p>No workflow files at this ref in the native selected directory.</p>}{selected && <Form onSubmit={event => { event.preventDefault(); void dispatch(); }}><h2>Dispatch {selected} at {ref}</h2><p>Forgejo validates workflow_dispatch and required inputs. A branch/tag may advance after this file listing. Dispatch creates a real provider run; it never registers a runner. Do not put credentials in inputs: use native Actions secrets.</p><label htmlFor="workflow-inputs">Native inputs (JSON object of strings)</label><textarea id="workflow-inputs" value={inputs} disabled={busy} maxLength={32768} onChange={event => setInputs(event.currentTarget.value)} /><Button type="submit" isDisabled={busy}>Dispatch native workflow</Button></Form>}{result && <p role="status">Created <Link to={`${base}/actions/runs/${result.id}`}>run #{result.number}</Link></p>}</section>;
}
