import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, expect, it, vi } from "vite-plus/test";
import { FileEditor } from "./file-editor";
import type { Session } from "./api";
import { useSession } from "./session";
const alice: Session = { user: { id: "1", login: "alice", soda_display_name: "Alice" }, csrf_token: "csrf", soda_operator: false, forgejo_url: "https://forgejo.example" };
afterEach(() => { cleanup(); vi.unstubAllGlobals(); useSession.setState({ session: null, phase: "anonymous" }); });
it("sends the loaded SHA once and retains the draft on a native conflict", async () => {
  const sha = "a".repeat(40);
  const fetcher = vi.fn(async (_path: string, options: RequestInit) => new Response(JSON.stringify(options.method === "PUT" ? { error: { code: "provider_conflict", message: "Forgejo reported a conflict; reload before editing." } } : { items: [{ type: "file", sha, text: "old" }] }), { status: options.method === "PUT" ? 409 : 200, headers: { "Content-Type": "application/json" } }));
  vi.stubGlobal("fetch", fetcher); useSession.setState({ session: alice, phase: "authenticated" });
  render(<MemoryRouter initialEntries={["/repositories/alice/demo/edit?ref=feature%2Fone&path=file.txt"]}><Routes><Route path="/repositories/:owner/:repo/edit" element={<FileEditor session={alice} />} /></Routes></MemoryRouter>);
  const user = userEvent.setup(); const editor = await screen.findByDisplayValue("old"); await user.clear(editor); await user.type(editor, "new");
  await user.type(screen.getByLabelText(/Commit message/), "Update file"); await user.click(screen.getByRole("button", { name: "Commit file in Forgejo" }));
  await screen.findByText("Forgejo reported a conflict; reload before editing.");
  expect(screen.getByDisplayValue("new")).toBeTruthy();
  const writes = fetcher.mock.calls.filter(([, options]) => options.method === "PUT"); expect(writes).toHaveLength(1);
  expect(writes[0]?.[0]).toContain("ref=feature%2Fone"); expect(JSON.parse(String(writes[0]?.[1].body))).toEqual({ content: "bmV3", message: "Update file", sha });
});
