import { useEffect, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { Alert, Button, Form, FormGroup, Spinner, TextInput } from "@patternfly/react-core";
import { APIError, request, type Session } from "./api";
import { useSession } from "./session";
import { repositoryPath } from "./repositories";
import { Markdown } from "./markdown";
interface Release { id: string; name: string; tag_name: string; target_commitish: string; body: string; draft: boolean; prerelease: boolean; published_at: string; assets: { id: string; name: string; size: string; downloadable: boolean }[] }
export function Releases({ session }: { session: Session }) {
 const { owner = "", repo = "" } = useParams(); const [query, setQuery] = useSearchParams(); const page = query.get("page") ?? "1"; const base = repositoryPath(owner, repo); const api = `/api/forgejo/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/releases`;
 const [items, setItems] = useState<Release[] | null>(null); const [next, setNext] = useState<number | null>(null); const [error, setError] = useState("");
 useEffect(() => { const controller = new AbortController(); setItems(null); setError(""); request<{ items: Release[]; next_page: number | null }>(`${api}?page=${encodeURIComponent(page)}`, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) { setItems(value.items); setNext(value.next_page); } }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Releases unavailable."); }); return () => controller.abort(); }, [api, page, session]);
 return <section><h1>Releases: {owner}/{repo}</h1><nav><Link to={base}>Repository</Link><Link to={`${base}/releases/new`}>Create release</Link></nav>{error && <Alert isInline variant="danger" title={error} />}{!items && !error && <Spinner aria-label="Reading releases" />}<ul>{items?.map(item => <li key={item.id}><Link to={`${base}/releases/${item.id}`}>{item.name || item.tag_name}</Link> — {item.draft ? "draft" : "published"}{item.prerelease ? " (prerelease)" : ""} — {item.tag_name}</li>)}</ul>{items?.length === 0 && <p>No visible releases on this page.</p>}<Button variant="secondary" isDisabled={Number(page) <= 1} onClick={() => setQuery({ page: String(Number(page) - 1) })}>Previous page</Button><Button variant="secondary" isDisabled={!items || next === null} onClick={() => next !== null && setQuery({ page: String(next) })}>Next page</Button></section>;
}
export function ReleaseDetail({ session }: { session: Session }) {
 const { owner = "", repo = "", release = "" } = useParams(); const base = repositoryPath(owner, repo); const api = `/api/forgejo/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/releases/${encodeURIComponent(release)}`;
 const [value, setValue] = useState<Release | null>(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0); const [busy, setBusy] = useState(false); const [file, setFile] = useState<File | null>(null); const [uploadKey, setUploadKey] = useState(0);
 useEffect(() => { const controller = new AbortController(); setValue(null); setError(""); request<Release>(api, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) setValue(result); }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Release unavailable."); }); return () => controller.abort(); }, [api, attempt, session]);
 async function upload() { if (busy || !file) return; if (file.size > 32768) { setError("Uploads are limited to 32 KiB. Use native Forgejo for larger assets."); return; } setBusy(true); setError(""); try { const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); if (useSession.getState().session !== session) return; await request(`${api}/assets`, { method: "POST", csrf: session.csrf_token, body: { name: file.name, content: btoa(binary) } }); if (useSession.getState().session === session) { setFile(null); setUploadKey(key => key + 1); setAttempt(key => key + 1); } } catch (failure) { if (useSession.getState().session !== session) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(`${failure instanceof Error ? failure.message : "Upload not confirmed."} Inspect native assets before retrying.`); } finally { setBusy(false); } }
 return <section aria-busy={busy}><h1>Release</h1><Link to={`${base}/releases`}>Releases</Link>{error && <Alert isInline variant="danger" title={error} />}{!value && !error && <Spinner aria-label="Reading release" />}{value && <><h2>{value.name || value.tag_name}</h2><p>{value.tag_name} — {value.draft ? "draft" : "published"}{value.prerelease ? " — prerelease" : ""}</p><Link to={`${base}/releases/${value.id}/edit`}>Edit release</Link><Markdown text={value.body} repository={{ route: base, ref: value.tag_name, path: "" }} /><h3>Assets</h3><ul>{value.assets.map(asset => <li key={asset.id}>{asset.downloadable ? <a href={`${api}/assets/${asset.id}/download`}>{asset.name}</a> : <>{asset.name} — download unavailable in Soda (external or beyond supported bound)</>} — {asset.size} bytes</li>)}</ul><p>Larger and external asset downloads still require integration in Soda.</p><Form onSubmit={event => { event.preventDefault(); void upload(); }}><label htmlFor="release-file">Upload asset (at most 32 KiB)</label><input key={uploadKey} id="release-file" type="file" disabled={busy} onChange={event => setFile(event.currentTarget.files?.[0] ?? null)} /><Button type="submit" isDisabled={busy || !file}>Upload native asset</Button></Form></>}</section>;
}
export function ReleaseEditor({ session }: { session: Session }) {
 const { owner = "", repo = "", release } = useParams(); const base = repositoryPath(owner, repo); const api = `/api/forgejo/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/releases`;
 const [loaded, setLoaded] = useState<Release | null>(null); const [name, setName] = useState(""); const [tag, setTag] = useState(""); const [target, setTarget] = useState(""); const [body, setBody] = useState(""); const [draft, setDraft] = useState(true); const [prerelease, setPrerelease] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [result, setResult] = useState<Release | null>(null);
 useEffect(() => { if (!release) return; const controller = new AbortController(); request<Release>(`${api}/${encodeURIComponent(release)}`, { signal: controller.signal }).then(value => { if (controller.signal.aborted) return; setLoaded(value); setName(value.name); setTag(value.tag_name); setTarget(value.target_commitish); setBody(value.body); setDraft(value.draft); setPrerelease(value.prerelease); }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Release unavailable."); }); return () => controller.abort(); }, [api, release, session]);
 async function save() { if (busy || (release && !loaded)) return; setBusy(true); setError(""); setResult(null); const fields = { name, tag_name: tag, target_commitish: target, body, draft, prerelease }; const changes = loaded ? Object.fromEntries(Object.entries(fields).filter(([key, value]) => value !== loaded[key as keyof Release])) : fields;
 try { const value = await request<Release>(release ? `${api}/${encodeURIComponent(release)}` : api, { method: release ? "PATCH" : "POST", csrf: session.csrf_token, body: changes }); if (useSession.getState().session === session) { setResult(value); setLoaded(value); } } catch (failure) { if (useSession.getState().session !== session) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(`${failure instanceof Error ? failure.message : "Release change not confirmed."} Inspect native releases before retrying.`); } finally { setBusy(false); } }
 return <section aria-busy={busy}><h1>{release ? "Edit release" : "Create release"}</h1><Link to={`${base}/releases`}>Releases</Link>{error && <Alert isInline variant="danger" title={error} />}{release && !loaded && !error && <Spinner aria-label="Reading release for editing" />}<p>Forgejo owns tags, publication and permissions. New releases start as drafts here. Edits submit changed fields only and retain native last-write semantics. The pinned PATCH cannot clear an existing title/body.</p><Form onSubmit={event => { event.preventDefault(); void save(); }}><FormGroup label="Title" fieldId="release-name"><TextInput id="release-name" value={name} isDisabled={busy} maxLength={255} onChange={(_, value) => setName(value)} /></FormGroup><FormGroup label="Tag" fieldId="release-tag"><TextInput id="release-tag" value={tag} isDisabled={busy} onChange={(_, value) => setTag(value)} /></FormGroup><FormGroup label="Target ref" fieldId="release-target"><TextInput id="release-target" value={target} isDisabled={busy} onChange={(_, value) => setTarget(value)} /></FormGroup><label htmlFor="release-body">Markdown notes</label><textarea id="release-body" value={body} disabled={busy} maxLength={32768} onChange={event => setBody(event.currentTarget.value)} /><label><input type="checkbox" checked={draft} disabled={busy} onChange={event => setDraft(event.currentTarget.checked)} /> Keep as draft (unchecking publishes)</label><label><input type="checkbox" checked={prerelease} disabled={busy} onChange={event => setPrerelease(event.currentTarget.checked)} /> Prerelease</label><Button type="submit" isDisabled={busy || !!result || !tag || !target || (!!release && !loaded)}>Save native release</Button></Form>{result && <p role="status">Saved <Link to={`${base}/releases/${result.id}`}>{result.name || result.tag_name}</Link></p>}</section>;
}
