import { useEffect, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { Alert, Button, Form, FormGroup, FormSelect, FormSelectOption, Spinner, TextInput } from "@patternfly/react-core";
import { APIError, request, type Session } from "./api";
import { useSession } from "./session";
import type { Organization } from "./organizations";
interface Team { id: string; name: string; description: string; organization: Organization; permission: string; includes_all_repositories: boolean; can_create_org_repo: boolean; units_map: Record<string, string> | null }
export function OrganizationTeams({ session, org }: { session: Session; org: string }) {
  const [query, setQuery] = useSearchParams(); const page = query.get("page") ?? "1"; const api = `/api/forgejo/organizations/${encodeURIComponent(org)}/teams`;
  const [items, setItems] = useState<Team[] | null>(null); const [next, setNext] = useState<number | null>(null); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [permission, setPermission] = useState("read"); const [attempt, setAttempt] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => {
    const controller = new AbortController(); setItems(null); setError("");
    request<{ items: Team[]; next_page: number | null }>(`${api}?page=${encodeURIComponent(page)}`, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) { setItems(value.items); setNext(value.next_page); } }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Native teams unavailable."); }); return () => controller.abort();
  }, [api, page, attempt, session]);
  async function create() {
    if (busy) return; setBusy(true); setError("");
    try {
      await request(api, { method: "POST", body: { name, description, permission, ...(permission !== "admin" ? { units_map: { "repo.code": permission, "repo.issues": permission, "repo.pulls": permission } } : {}) }, csrf: session.csrf_token });
      if (useSession.getState().session === session) { setName(""); setDescription(""); setAttempt(value => value + 1); }
    } catch (failure) { if (useSession.getState().session !== session) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Team creation not confirmed."); } finally { setBusy(false); }
  }
  return <section aria-busy={busy}><h2>Native teams</h2>{error && <Alert isInline variant="warning" title={error} />}{!items && !error && <Spinner aria-label="Loading teams" />}<ul>{items?.map(team => <li key={team.id}><Link to={`/teams/${team.id}`}>{team.name}</Link> — {team.permission}</li>)}</ul><Button variant="secondary" isDisabled={busy || Number(page) <= 1} onClick={() => setQuery({ tab: "teams", page: String(Number(page) - 1) })}>Previous page</Button><Button variant="secondary" isDisabled={busy || next === null} onClick={() => next !== null && setQuery({ tab: "teams", page: String(next) })}>Next page</Button>
    <h3>Create native team</h3><p>New read/write teams explicitly receive code, issue and pull-request units only. Native administrator teams receive Forgejo's administrator units. Repository assignment and membership remain separate explicit operations.</p>
    <Form onSubmit={event => { event.preventDefault(); void create(); }}><FormGroup label="Team name" fieldId="team-name"><TextInput id="team-name" value={name} isDisabled={busy} onChange={(_, value) => setName(value)} /></FormGroup><FormGroup label="Team description" fieldId="team-description"><TextInput id="team-description" value={description} isDisabled={busy} onChange={(_, value) => setDescription(value)} /></FormGroup><FormGroup label="Native team permission" fieldId="team-permission"><FormSelect id="team-permission" value={permission} isDisabled={busy} onChange={(_, value) => setPermission(value)}>{["read", "write", "admin"].map(value => <FormSelectOption key={value} value={value} label={value} />)}</FormSelect></FormGroup><Button type="submit" isDisabled={busy || !name}>Create native team</Button></Form>
  </section>;
}
function TeamMembers({ session, id }: { session: Session; id: string }) {
  const [query, setQuery] = useSearchParams(); const page = query.get("page") ?? "1"; const api = `/api/forgejo/teams/${encodeURIComponent(id)}/members`;
  const [items, setItems] = useState<{ id: string; login: string }[] | null>(null); const [next, setNext] = useState<number | null>(null); const [login, setLogin] = useState(""); const [confirm, setConfirm] = useState(false); const [attempt, setAttempt] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => {
    const controller = new AbortController(); setItems(null); setError(""); request<{ items: { id: string; login: string }[]; next_page: number | null }>(`${api}?page=${encodeURIComponent(page)}`, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) { setItems(value.items); setNext(value.next_page); } }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Team members unavailable."); }); return () => controller.abort();
  }, [api, page, attempt, session]);
  async function save(remove: boolean) {
    if (busy || (remove && !confirm)) return; setBusy(true); setError("");
    try { await request(`${api}/${encodeURIComponent(login)}`, { method: remove ? "DELETE" : "PUT", body: {}, csrf: session.csrf_token }); if (useSession.getState().session === session) { setConfirm(false); setAttempt(value => value + 1); } }
    catch (failure) { if (useSession.getState().session !== session) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Native team membership change not confirmed."); } finally { setBusy(false); }
  }
  return <section aria-busy={busy}><h2>Native team members</h2>{error && <Alert isInline variant="warning" title={error} />}<ul>{items?.map(user => <li key={user.id}>{user.login}</li>)}</ul><Button variant="secondary" isDisabled={busy || Number(page) <= 1} onClick={() => setQuery({ tab: "members", page: String(Number(page) - 1) })}>Previous page</Button><Button variant="secondary" isDisabled={busy || next === null} onClick={() => next !== null && setQuery({ tab: "members", page: String(next) })}>Next page</Button>
    <Form onSubmit={event => { event.preventDefault(); void save(false); }}><FormGroup label="Native username" fieldId="team-member-login"><TextInput id="team-member-login" value={login} isDisabled={busy} onChange={(_, value) => { setLogin(value); setConfirm(false); }} /></FormGroup><Button type="submit" isDisabled={busy || !login}>Add native team member</Button><label><input type="checkbox" checked={confirm} disabled={busy} onChange={event => setConfirm(event.currentTarget.checked)} /> Remove {login || "entered user"} from this native team only</label><Button variant="danger" isDisabled={busy || !login || !confirm} onClick={() => void save(true)}>Remove native team member</Button></Form><p>No Linux account/key revocation occurs. Other native team access may remain.</p>
  </section>;
}
function TeamRepositories({ session, id }: { session: Session; id: string }) {
  const [query, setQuery] = useSearchParams(); const page = query.get("page") ?? "1"; const api = `/api/forgejo/teams/${encodeURIComponent(id)}/repositories`;
  const [items, setItems] = useState<{ id: string; full_name: string }[] | null>(null); const [next, setNext] = useState<number | null>(null); const [owner, setOwner] = useState(""); const [repo, setRepo] = useState(""); const [confirm, setConfirm] = useState(false); const [attempt, setAttempt] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => {
    const controller = new AbortController(); setItems(null); setError(""); request<{ items: { id: string; full_name: string }[]; next_page: number | null }>(`${api}?page=${encodeURIComponent(page)}`, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) { setItems(value.items); setNext(value.next_page); } }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Team repositories unavailable."); }); return () => controller.abort();
  }, [api, page, attempt, session]);
  async function save(remove: boolean) {
    if (busy || (remove && !confirm)) return; setBusy(true); setError("");
    try { await request(`${api}/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`, { method: remove ? "DELETE" : "PUT", body: {}, csrf: session.csrf_token }); if (useSession.getState().session === session) { setConfirm(false); setAttempt(value => value + 1); } }
    catch (failure) { if (useSession.getState().session !== session) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Native repository assignment not confirmed."); } finally { setBusy(false); }
  }
  return <section aria-busy={busy}><h2>Native team repositories</h2>{error && <Alert isInline variant="warning" title={error} />}<ul>{items?.map(repo => <li key={repo.id}>{repo.full_name}</li>)}</ul><Button variant="secondary" isDisabled={busy || Number(page) <= 1} onClick={() => setQuery({ tab: "repositories", page: String(Number(page) - 1) })}>Previous page</Button><Button variant="secondary" isDisabled={busy || next === null} onClick={() => next !== null && setQuery({ tab: "repositories", page: String(next) })}>Next page</Button>
    <Form onSubmit={event => { event.preventDefault(); void save(false); }}><FormGroup label="Native repository owner" fieldId="team-repo-owner"><TextInput id="team-repo-owner" value={owner} isDisabled={busy} onChange={(_, value) => { setOwner(value); setConfirm(false); }} /></FormGroup><FormGroup label="Native repository name" fieldId="team-repo-name"><TextInput id="team-repo-name" value={repo} isDisabled={busy} onChange={(_, value) => { setRepo(value); setConfirm(false); }} /></FormGroup><Button type="submit" isDisabled={busy || !owner || !repo}>Assign native repository to team</Button><label><input type="checkbox" checked={confirm} disabled={busy} onChange={event => setConfirm(event.currentTarget.checked)} /> Remove this native team assignment for {owner}/{repo}</label><Button variant="danger" isDisabled={busy || !owner || !repo || !confirm} onClick={() => void save(true)}>Remove native repository assignment</Button></Form><p>Forgejo checks the team's real organization and repository administration authority. This neither creates nor joins an environment.</p>
  </section>;
}
export function TeamDetail({ session }: { session: Session }) {
  const { team = "" } = useParams(); const [query, setQuery] = useSearchParams(); const tab = query.get("tab") ?? "members"; const [value, setValue] = useState<Team | null>(null); const [description, setDescription] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => {
    const controller = new AbortController(); setValue(null); setError(""); request<Team>(`/api/forgejo/teams/${encodeURIComponent(team)}`, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) { setValue(result); setDescription(result.description); } }).catch(failure => { if (controller.signal.aborted) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Native team unavailable."); }); return () => controller.abort();
  }, [team, session]);
  async function saveDescription() {
    if (busy) return; setBusy(true); setError("");
    try { const result = await request<Team>(`/api/forgejo/teams/${encodeURIComponent(team)}`, { method: "PATCH", body: { description }, csrf: session.csrf_token }); if (useSession.getState().session === session) setValue(result); }
    catch (failure) { if (useSession.getState().session !== session) return; if (failure instanceof APIError && failure.status === 401) useSession.getState().invalidate(session); else setError(failure instanceof Error ? failure.message : "Native team settings not confirmed."); } finally { setBusy(false); }
  }
  return <section aria-busy={busy}><h1>Native team: {value?.name || team}</h1>{error && <Alert isInline variant="danger" title={error} />}{!value && !error && <Spinner aria-label="Loading team" />}{value && <><Link to={`/organizations/${encodeURIComponent(value.organization.name)}`}>Organization {value.organization.name}</Link><p>{value.description} — native permission {value.permission}; all repositories: {String(value.includes_all_repositories)}; repository creation: {String(value.can_create_org_repo)}.</p><ul>{Object.entries(value.units_map ?? {}).map(([unit, permission]) => <li key={unit}>{unit}: {permission}</li>)}</ul>
    <nav aria-label="Team tabs">{["members", "repositories", "settings"].map(value => <Button key={value} variant={tab === value ? "primary" : "secondary"} onClick={() => setQuery({ tab: value })}>{value}</Button>)}</nav>{tab === "members" && <TeamMembers session={session} id={team} />}{tab === "repositories" && <TeamRepositories session={session} id={team} />}{tab === "settings" && <><Form onSubmit={event => { event.preventDefault(); void saveDescription(); }}><FormGroup label="Native team description" fieldId="edit-team-description"><TextInput id="edit-team-description" value={description} isDisabled={busy} onChange={(_, value) => setDescription(value)} /></FormGroup><Button type="submit" isDisabled={busy}>Save native team description</Button></Form><p>Per-unit permission and repository-creation policy editors remain unfinished custom source. The explicit API supports bounded native fields; no local team policy store exists.</p></>}
  </>}</section>;
}
