[package]
name = "soda-image-import"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "soda-image-import"
path = "src/main.rs"

[dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", features = ["raw_value"] }
sha2 = "=0.10.9"
soda-json = { path = "../../lib/json" }
