[package]
name = "soda-install"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "soda-install"
path = "src/main.rs"

[dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", features = ["raw_value"] }
base64 = "=0.22.1"
getrandom = { version = "=0.4.3", features = ["std"] }
soda-json = { path = "../../lib/json" }
libc = "=0.2.190"
sha2 = { version = "0.10", features = ["oid"] }
elliptic-curve = "0.13"
p224 = "0.13"
p256 = "0.13"
p384 = "0.13"
p521 = "0.13"
rsa = "0.9"
ecdsa = { version = "=0.16.9", default-features = false, features = ["verifying", "pkcs8", "std"] }
signature = "2"
ed25519-dalek = { version = "2", default-features = false, features = ["alloc", "fast", "zeroize"] }
