[package]
name = "soda-host"
version = "0.1.0"
edition = "2021"

[lib]
name = "soda_host"
path = "src/lib.rs"

[[bin]]
name = "soda-host"
path = "src/main.rs"

[dependencies]
libc = "0.2"
soda-release-deliver = { path = "../../lib/soda-release-deliver" }
soda-release-build = { path = "../../lib/soda-release-build" }
